- name: Copy MySQL Repo Files
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Client Version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL Client Server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: Start MySQL Client Server
  ansible.builtin.systemd:
    name: mysqld
    state: restarted

- name: Setup root Password for MySQL Client Server
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

