route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: "email"
    email_configs:
      - to: glasshouse747@gmail.com
        from: glasshouse747@gmail.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: {{ lookup('aws_ssm', 'prometheus.email.username', region='us-east-1' ) }}
        auth_password: {{ lookup('aws_ssm', 'prometheus.email.password', region='us-east-1' ) }}
        require_tls: true
